name: producer__c
filterable: false
hidden: false
index: false
is_name: false
is_wide: false
label: 制造商
omit: false
readonly: false
required: false
searchable: false
sort_no: 160
sortable: false
type: text
