name: service_tool_application__c
custom: true
enable_api: true
enable_audit: false
enable_chatter: false
enable_events: false
enable_files: false
enable_inline_edit: true
enable_instances: false
enable_notes: false
enable_search: true
enable_share: false
enable_tasks: false
enable_workflow: false
icon: macros
is_enable: true
label: 工具申请
